### PR TITLE
Update to xcode11.5/Swift 5-compatible Regex cart

### PR DESCRIPTION
**Pull request by apparition47**
* updated Regex cart to 2.1.1

### CODE REVIEW

**Comment by ashchan** [comment]
👍  (guess we could move on and just migrate to SPM. Only one dep :p)

**Comment by apparition47** [comment]
Good idea. Completely forgot about SPM. 😅

**Comment by ashchan** [comment]
Migrated to SPM. eaa61abffb3f4b33929ebd02386b8243f2a02488

**Comment by ashchan** [comment]
@apparition47 Thanks for the update. I've uploaded 2.5 for review.

**Comment by ashchan** [comment]
2.5 ready for ‘sale’. Might take a few hours to appear in the store.

**Comment by apparition47** [comment]
Cool! Thanks!

**Pull request merged**
